### PR TITLE
Fix bugs, add tests and static typing

### PR DESCRIPTION
**Pull request by fionn**
Hey,

Thanks for this package. Hopefully you'll find my contributions beneficial and not too drastic. I fixed a couple of bugs and removed ambiguity around what the various methods return. There's also unit tests now.

Let me know if you'd like me to change anything.

* Remove shebang on non-executable files
* Remove json import (requests can dump to json for us)
* Inherit from object implicitly
* Unmangle private members
* Tabs --> spaces
* Fix bug where session property had incinsistent return behaviour
* Explicitly raise for a bad response instead of catching it and masking erors
* Add type annotations to methods and arguments
* Fix typing errors in docstrings
* Add unit tests
* Restrict to Python3 now (for typing, urllib.parse)

### CODE REVIEW

**Comment by barnumbirr** [comment]
Ohai,

thank you for the PR. I'll take a look over the weekend and I'll come back to you.

Cheers.

**Comment by fionn** [comment]
Hey, I hope you had good weekends! Any thoughts on this?

**Comment by fionn** [comment]
I'm gonna delete my fork and close this PR soon.

**Comment by barnumbirr** [comment]
Hello,

I've finally took the time to quickly look into this. First of all: thank you for the PR!
I'm not a fan of static typing nor the restriction to Python3+. Is that something you would consider changing?

Cheers.

**Comment by fionn** [comment]
Hi. Hmm, probably not, I am definitely a fan of static typing and don't see much point in supporting 2.7 any more. (Only 8 months until end-of-life anyway.)

But I think the only reason this is restricted to 3.x is the type annotations, so I'll strip those out and just maintain my statically typed 3.x-only fork. Assuming you're happy with everything else?

**Comment by barnumbirr** [comment]
Still not a fan of static typing. Even though Python is EOL, ares is capable of supporting it quite easily. Some impreovement added to v0.6.0/v0.6.1 though.

Thanks a lot.

**Pull request closed without merging**
